### ISSUE TITLE
Shouldn't ThreadStatus be Result<(), LuaError> ?

### ISSUE THREAD

**Issue by tailhook** [jcmoyer/rust-lua53#20]
It's easier to handle error reporting by dealing with `Result` that by matching on each step. For example, you might use `try!`, `map/map_err`, etc.

**Comment by jcmoyer** [comment]
I think the reason I wrote it that way is because `LUA_OK` and `LUA_YIELD` both represent 'good' statuses. At some point I wanted to change functions returning `ThreadStatus` to return `Result<something, something>` but I couldn't figure out how to best rework it without departing too much from the original design. It seems there needs to be a way to categorize values of `ThreadStatus` as 'good' or 'bad'. I don't think it's semantically correct for the `Err` variant to be able to contain values of `LUA_OK` and `LUA_YIELD`.

**Comment by tailhook** [comment]
Yes, and we probably need some better wrapper anyway. The one that also returns the Lua error description.

I think higher level "pcall" should also push arguments automatically. So I close this one now, and may open a issue/pull request with more specific proposal.

**Comment by Parakleta** [comment]
I think for this you should reduce `ThreadStatus` to only include the good conditions and create an `ThreadError` type for the others.  Then anything that would return a `ThreadStatus` currently should return a `Result<ThreadStatus, ThreadError>`.
